package net.thep2wking.badores.init;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.thep2wking.badores.BadOres;
import net.thep2wking.badores.content.block.BlockAmadeum;
import net.thep2wking.badores.content.block.BlockAppetite;
import net.thep2wking.badores.content.block.BlockBalancium;
import net.thep2wking.badores.content.block.BlockBreakium;
import net.thep2wking.badores.content.block.BlockCrashium;
import net.thep2wking.badores.content.block.BlockDiamondOre;
import net.thep2wking.badores.content.block.BlockEnderite;
import net.thep2wking.badores.content.block.BlockExplodeitmite;
import net.thep2wking.badores.content.block.BlockFleesonsite;
import net.thep2wking.badores.content.block.BlockGhostium;
import net.thep2wking.badores.content.block.BlockIdlikeabite;
import net.thep2wking.badores.content.block.BlockKakkarite;
import net.thep2wking.badores.content.block.BlockKillium;
import net.thep2wking.badores.content.block.BlockMeteorite;
import net.thep2wking.badores.content.block.BlockMisleadium;
import net.thep2wking.badores.content.block.BlockMovium;
import net.thep2wking.badores.content.block.BlockNosleeptonite;
import net.thep2wking.badores.content.block.BlockPaintitwhite;
import net.thep2wking.badores.content.block.BlockPandaemonium;
import net.thep2wking.badores.content.block.BlockPolite;
import net.thep2wking.badores.content.block.BlockShiftium;
import net.thep2wking.badores.content.block.BlockSmite;
import net.thep2wking.badores.content.block.BlockStonium;
import net.thep2wking.badores.content.block.BlockStreetscum;
import net.thep2wking.badores.content.block.BlockTauntum;
import net.thep2wking.badores.content.block.BlockWannafite;
import net.thep2wking.badores.content.block.BlockWantarite;
import net.thep2wking.badores.content.block.BlockWebsite;
import net.thep2wking.badores.content.block.BlockZombieunite;
import net.thep2wking.reloadedlib.api.block.ModBlockBase;
import net.thep2wking.reloadedlib.api.block.ModBlockOreBase;
import net.thep2wking.reloadedlib.util.ModToolTypes;

public class ModBlocks {
	public static final Block POLITE = new BlockPolite(BadOres.MODID, "polite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block WANNAFITE = new BlockWannafite(BadOres.MODID, "wannafite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block BREAKIUM = new BlockBreakium(BadOres.MODID, "breakium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block STONIUM = new BlockStonium(BadOres.MODID, "stonium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block CRAPPIUM = new ModBlockOreBase(BadOres.MODID, "crappium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block ENDERITE = new BlockEnderite(BadOres.MODID, "enderite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block WEBSITE = new BlockWebsite(BadOres.MODID, "website", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block LITE = new ModBlockOreBase(BadOres.MODID, "lite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 10);
	public static final Block MISLEADIUM = new BlockMisleadium(BadOres.MODID, "misleadium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block GHOSTIUM = new BlockGhostium(BadOres.MODID, "ghostium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block AMADEUM = new BlockAmadeum(BadOres.MODID, "amadeum", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block BARELYGENERITE = new ModBlockOreBase(BadOres.MODID, "barelygenerite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block UNOBTAINIUM = new ModBlockOreBase(BadOres.MODID, "unobtainium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, -1, ModToolTypes.PICKAXE, -1, 3600000f, 0);
	public static final Block COPPER_ORE = new ModBlockOreBase(BadOres.MODID, "copper_ore", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block USELESSIUM = new ModBlockOreBase(BadOres.MODID, "uselessium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block KILLIUM = new BlockKillium(BadOres.MODID, "killium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block MOVIUM = new BlockMovium(BadOres.MODID, "movium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block BALANCIUM = new BlockBalancium(BadOres.MODID, "balancium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block EXPLODEITMITE = new BlockExplodeitmite(BadOres.MODID, "explodeitmite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 10.0f, 10.0f, 0);
	public static final Block MARMITE = new ModBlockOreBase(BadOres.MODID, "marmite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.GROUND, MapColor.CLAY, 0, ModToolTypes.SHOVEL, 1.5f, 1.5f, 0);
	public static final Block SHIFTIUM = new BlockShiftium(BadOres.MODID, "shiftium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block WANTARITE = new BlockWantarite(BadOres.MODID, "wantarite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block IDLIKEABITE = new BlockIdlikeabite(BadOres.MODID, "idlikeabite", BadOres.TAB, 0, 0, Material.GOURD, SoundType.GROUND, MapColor.DIRT, 0, ModToolTypes.SHOVEL, 1.5f, 1.5f, 0);
	public static final Block METEORITE = new BlockMeteorite(BadOres.MODID, "meteorite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block STREETSCUM = new BlockStreetscum(BadOres.MODID, "streetscum", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block FLEESONSITE = new BlockFleesonsite(BadOres.MODID, "fleesonsite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block NOPIUM = new ModBlockOreBase(BadOres.MODID, "nopium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block ZOMBIEUNITE = new BlockZombieunite(BadOres.MODID, "zombieunite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block PAINTITWHITE = new BlockPaintitwhite(BadOres.MODID, "paintitwhite", BadOres.TAB, 0, 0, Material.GROUND, SoundType.GROUND, MapColor.GRAY, 0, ModToolTypes.SHOVEL, 1.5f, 1.5f, 0);
	public static final Block IWONTFITE = new ModBlockOreBase(BadOres.MODID, "iwontfite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block TAUNTUM = new BlockTauntum(BadOres.MODID, "tauntum", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block PANDAEMONIUM = new BlockPandaemonium(BadOres.MODID, "pandaemonium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block NOSLEEPTONITE = new BlockNosleeptonite(BadOres.MODID, "nosleeptonite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block APPETITE = new BlockAppetite(BadOres.MODID, "appetite", BadOres.TAB, 0, 0, Material.SAND, SoundType.SAND, MapColor.SAND, 0, ModToolTypes.SHOVEL, 1.5f, 1.5f, 0);
	public static final Block CRASHIUM = new BlockCrashium(BadOres.MODID, "crashium", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block SMITE = new BlockSmite(BadOres.MODID, "smite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block DIAMOND_ORE = new BlockDiamondOre(BadOres.MODID, "diamond_ore", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);
	public static final Block KAKKARITE = new BlockKakkarite(BadOres.MODID, "kakkarite", BadOres.TAB, 0, 0, Material.ROCK, SoundType.STONE, MapColor.STONE, 1, ModToolTypes.PICKAXE, 3.0f, 3.0f, 0);

	public static final Block POLITE_BLOCK = new ModBlockBase(BadOres.MODID, "polite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.YELLOW, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block CRAPPIUM_BLOCK = new ModBlockBase(BadOres.MODID, "crappium_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.LIME, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block ENDERITE_BLOCK = new ModBlockBase(BadOres.MODID, "enderite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.CYAN, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block AMADEUM_BLOCK = new ModBlockBase(BadOres.MODID, "amadeum_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.LIME, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block BARELYGENERITE_BLOCK = new ModBlockBase(BadOres.MODID, "barelygenerite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.ADOBE, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block COPPER_BLOCK = new ModBlockBase(BadOres.MODID, "copper_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.ORANGE_STAINED_HARDENED_CLAY, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block MARMITE_BLOCK = new ModBlockBase(BadOres.MODID, "marmite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.BROWN, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block FLEESONSITE_BLOCK = new ModBlockBase(BadOres.MODID, "fleesonsite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.LIGHT_BLUE, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block NOPIUM_BLOCK = new ModBlockBase(BadOres.MODID, "nopium_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.GOLD, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block NOSLEEPTONITE_BLOCK = new ModBlockBase(BadOres.MODID, "nosleeptonite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.ORANGE_STAINED_HARDENED_CLAY, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block CRASHIUM_BLOCK = new ModBlockBase(BadOres.MODID, "crashium_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.GREEN, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block SMITE_BLOCK = new ModBlockBase(BadOres.MODID, "smite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.LIGHT_BLUE, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block DIAMOND_BLOCK = new ModBlockBase(BadOres.MODID, "diamond_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.DIAMOND, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
	public static final Block KAKKARITE_BLOCK = new ModBlockBase(BadOres.MODID, "kakkarite_block", BadOres.TAB, Material.IRON, SoundType.METAL, MapColor.DIAMOND, 1, ModToolTypes.PICKAXE, 5.0f, 5.0f, 0);
}