package net.thep2wking.badores.init;

import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.thep2wking.badores.BadOres;
import net.thep2wking.badores.content.item.ItemAmadeumArmor;
import net.thep2wking.badores.content.item.ItemAmadeumAxe;
import net.thep2wking.badores.content.item.ItemAmadeumHoe;
import net.thep2wking.badores.content.item.ItemAmadeumPickaxe;
import net.thep2wking.badores.content.item.ItemAmadeumShovel;
import net.thep2wking.badores.content.item.ItemAmadeumSword;
import net.thep2wking.badores.content.item.ItemCrashiumArmor;
import net.thep2wking.badores.content.item.ItemCrashiumAxe;
import net.thep2wking.badores.content.item.ItemCrashiumHoe;
import net.thep2wking.badores.content.item.ItemCrashiumPickaxe;
import net.thep2wking.badores.content.item.ItemCrashiumShovel;
import net.thep2wking.badores.content.item.ItemCrashiumSword;
import net.thep2wking.badores.content.item.ItemDiamondArmor;
import net.thep2wking.badores.content.item.ItemEnderiteArmor;
import net.thep2wking.badores.content.item.ItemEnderiteAxe;
import net.thep2wking.badores.content.item.ItemEnderiteHoe;
import net.thep2wking.badores.content.item.ItemEnderitePickaxe;
import net.thep2wking.badores.content.item.ItemEnderiteShovel;
import net.thep2wking.badores.content.item.ItemEnderiteSword;
import net.thep2wking.badores.content.item.ItemNopiumArmor;
import net.thep2wking.badores.content.item.ItemNopiumAxe;
import net.thep2wking.badores.content.item.ItemNopiumHoe;
import net.thep2wking.badores.content.item.ItemNopiumIngot;
import net.thep2wking.badores.content.item.ItemNopiumPickaxe;
import net.thep2wking.badores.content.item.ItemNopiumShovel;
import net.thep2wking.badores.content.item.ItemNopiumSword;
import net.thep2wking.badores.content.item.ItemPoliteArmor;
import net.thep2wking.badores.content.item.ItemPoliteAxe;
import net.thep2wking.badores.content.item.ItemPoliteHoe;
import net.thep2wking.badores.content.item.ItemPolitePickaxe;
import net.thep2wking.badores.content.item.ItemPoliteShovel;
import net.thep2wking.badores.content.item.ItemPoliteSword;
import net.thep2wking.badores.content.item.ItemSmiteArmor;
import net.thep2wking.badores.content.item.ItemSmiteAxe;
import net.thep2wking.badores.content.item.ItemSmiteHoe;
import net.thep2wking.badores.content.item.ItemSmitePickaxe;
import net.thep2wking.badores.content.item.ItemSmiteShovel;
import net.thep2wking.badores.content.item.ItemSmiteSword;
import net.thep2wking.badores.content.itemblock.ItemBlockFleesonsite;
import net.thep2wking.badores.content.itemblock.ItemBlockIdlikeabite;
import net.thep2wking.badores.content.itemblock.ItemBlockIwontfite;
import net.thep2wking.badores.content.itemblock.ItemBlockKillium;
import net.thep2wking.badores.content.itemblock.ItemBlockNopium;
import net.thep2wking.badores.util.ModArmorMaterial;
import net.thep2wking.badores.util.ModToolMaterial;
import net.thep2wking.oedldoedlcore.api.armor.ModItemArmorBase;
import net.thep2wking.oedldoedlcore.api.item.ModItemBase;
import net.thep2wking.oedldoedlcore.api.item.ModItemBlockBase;
import net.thep2wking.oedldoedlcore.api.item.ModItemFoodBase;
import net.thep2wking.oedldoedlcore.api.tool.ModItemAxeBase;
import net.thep2wking.oedldoedlcore.api.tool.ModItemHoeBase;
import net.thep2wking.oedldoedlcore.api.tool.ModItemPickaxeBase;
import net.thep2wking.oedldoedlcore.api.tool.ModItemShovelBase;
import net.thep2wking.oedldoedlcore.api.tool.ModItemSwordBase;
import net.thep2wking.oedldoedlcore.util.ModRarities;

public class ModItems {	
	public static final Item POLITE = new ModItemBlockBase(ModBlocks.POLITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item WANNAFITE = new ModItemBlockBase(ModBlocks.WANNAFITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item BREAKIUM = new ModItemBlockBase(ModBlocks.BREAKIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item STONIUM = new ModItemBlockBase(ModBlocks.STONIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM = new ModItemBlockBase(ModBlocks.CRAPPIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE = new ModItemBlockBase(ModBlocks.ENDERITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item WEBSITE = new ModItemBlockBase(ModBlocks.WEBSITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item LITE = new ModItemBlockBase(ModBlocks.LITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item MISLEADIUM = new ModItemBlockBase(ModBlocks.MISLEADIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item GHOSTIUM = new ModItemBlockBase(ModBlocks.GHOSTIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM = new ModItemBlockBase(ModBlocks.AMADEUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item BARELYGENERITE = new ModItemBlockBase(ModBlocks.BARELYGENERITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item UNOBTAINIUM = new ModItemBlockBase(ModBlocks.UNOBTAINIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_ORE = new ModItemBlockBase(ModBlocks.COPPER_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item USELESSIUM = new ModItemBlockBase(ModBlocks.USELESSIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item KILLIUM = new ItemBlockKillium(ModBlocks.KILLIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item MOVIUM = new ModItemBlockBase(ModBlocks.MOVIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item BALANCIUM = new ModItemBlockBase(ModBlocks.BALANCIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item EXPLODEITMITE = new ModItemBlockBase(ModBlocks.EXPLODEITMITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item MARMITE = new ModItemBlockBase(ModBlocks.MARMITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item SHIFTIUM = new ModItemBlockBase(ModBlocks.SHIFTIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item WANTARITE = new ModItemBlockBase(ModBlocks.WANTARITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item IDLIKEABITE = new ItemBlockIdlikeabite(ModBlocks.IDLIKEABITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item METEORITE = new ModItemBlockBase(ModBlocks.METEORITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item STREETSCUM = new ModItemBlockBase(ModBlocks.STREETSCUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item FLEESONSITE = new ItemBlockFleesonsite(ModBlocks.FLEESONSITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM = new ItemBlockNopium(ModBlocks.NOPIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item ZOMBIEUNITE = new ModItemBlockBase(ModBlocks.ZOMBIEUNITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item PAINTITWHITE = new ModItemBlockBase(ModBlocks.PAINTITWHITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item TAUNTUM = new ModItemBlockBase(ModBlocks.TAUNTUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item IWONTFITE = new ItemBlockIwontfite(ModBlocks.IWONTFITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item PANDAEMONIUM = new ModItemBlockBase(ModBlocks.PANDAEMONIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item NOSLEEPTONITE = new ModItemBlockBase(ModBlocks.NOSLEEPTONITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item APPETITE = new ModItemBlockBase(ModBlocks.APPETITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM = new ModItemBlockBase(ModBlocks.CRASHIUM_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE = new ModItemBlockBase(ModBlocks.SMITE_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_ORE = new ModItemBlockBase(ModBlocks.DIAMOND_ORE, ModRarities.WHITE, false, 0, 0);
	public static final Item KAKKARITE = new ModItemBlockBase(ModBlocks.KAKKARITE_ORE, ModRarities.WHITE, false, 0, 0);

	public static final Item POLITE_BLOCK = new ModItemBlockBase(ModBlocks.POLITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_BLOCK = new ModItemBlockBase(ModBlocks.CRAPPIUM_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_BLOCK = new ModItemBlockBase(ModBlocks.ENDERITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_BLOCK = new ModItemBlockBase(ModBlocks.AMADEUM_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item BARELYGENERITE_BLOCK = new ModItemBlockBase(ModBlocks.BARELYGENERITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_BLOCK = new ModItemBlockBase(ModBlocks.COPPER_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item MARMITE_BLOCK = new ModItemBlockBase(ModBlocks.MARMITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item FLEESONSITE_BLOCK = new ModItemBlockBase(ModBlocks.FLEESONSITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_BLOCK = new ItemBlockNopium(ModBlocks.NOPIUM_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item NOSLEEPTONITE_BLOCK = new ModItemBlockBase(ModBlocks.NOSLEEPTONITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_BLOCK = new ModItemBlockBase(ModBlocks.CRASHIUM_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_BLOCK = new ModItemBlockBase(ModBlocks.SMITE_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_BLOCK = new ModItemBlockBase(ModBlocks.DIAMOND_BLOCK, ModRarities.WHITE, false, 0, 0);
	public static final Item KAKKARITE_BLOCK = new ModItemBlockBase(ModBlocks.KAKKARITE_BLOCK, ModRarities.WHITE, false, 0, 0);

	public static final Item POLITE_INGOT = new ModItemBase(BadOres.MODID, "polite_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_INGOT = new ModItemBase(BadOres.MODID, "crappium_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_INGOT = new ModItemBase(BadOres.MODID, "enderite_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_INGOT = new ModItemBase(BadOres.MODID, "amadeum_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item BARELYGENERITE_INGOT = new ModItemBase(BadOres.MODID, "barelygenerite_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_INGOT = new ModItemBase(BadOres.MODID, "copper_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item USELESSIUM_INGOT = new ModItemBase(BadOres.MODID, "uselessium_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item MARMITE_INGOT = new ModItemFoodBase(BadOres.MODID, "marmite_ingot", BadOres.TAB, 1, 1f, false, ModRarities.WHITE, false, 0, 0);
	public static final Item FLEESONSITE_INGOT = new ModItemBase(BadOres.MODID, "fleesonsite_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_INGOT = new ItemNopiumIngot(BadOres.MODID, "nopium_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item NOSLEEPTONITE_INGOT = new ModItemBase(BadOres.MODID, "nosleeptonite_ingot", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_GEMSTONE = new ModItemBase(BadOres.MODID, "crashium_gemstone", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_GEMSTONE = new ModItemBase(BadOres.MODID, "smite_gemstone", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND = new ModItemBase(BadOres.MODID, "diamond", BadOres.TAB, ModRarities.WHITE, false, 0, 0);
	public static final Item KAKKARITE_GEMSTONE = new ModItemBase(BadOres.MODID, "kakkarite_gemstone", BadOres.TAB, ModRarities.WHITE, false, 0, 0);

	public static final Item POLITE_SWORD = new ItemPoliteSword(BadOres.MODID, "polite_sword", BadOres.TAB, ModToolMaterial.POLITE, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_SHOVEL = new ItemPoliteShovel(BadOres.MODID, "polite_shovel", BadOres.TAB, ModToolMaterial.POLITE, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_PICKAXE = new ItemPolitePickaxe(BadOres.MODID, "polite_pickaxe", BadOres.TAB, ModToolMaterial.POLITE, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_AXE = new ItemPoliteAxe(BadOres.MODID, "polite_axe", BadOres.TAB, ModToolMaterial.POLITE, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_HOE = new ItemPoliteHoe(BadOres.MODID, "polite_hoe", BadOres.TAB, ModToolMaterial.POLITE, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_HELMET = new ItemPoliteArmor(BadOres.MODID, "polite_helmet", BadOres.TAB, ModArmorMaterial.POLITE, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_CHESTPLATE = new ItemPoliteArmor(BadOres.MODID, "polite_chestplate", BadOres.TAB, ModArmorMaterial.POLITE, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_LEGGINGS = new ItemPoliteArmor(BadOres.MODID, "polite_leggings", BadOres.TAB, ModArmorMaterial.POLITE, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item POLITE_BOOTS = new ItemPoliteArmor(BadOres.MODID, "polite_boots", BadOres.TAB, ModArmorMaterial.POLITE, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item CRAPPIUM_SWORD = new ModItemSwordBase(BadOres.MODID, "crappium_sword", BadOres.TAB, ModToolMaterial.CRAPPIUM, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_SHOVEL = new ModItemShovelBase(BadOres.MODID, "crappium_shovel", BadOres.TAB, ModToolMaterial.CRAPPIUM, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_PICKAXE = new ModItemPickaxeBase(BadOres.MODID, "crappium_pickaxe", BadOres.TAB, ModToolMaterial.CRAPPIUM, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_AXE = new ModItemAxeBase(BadOres.MODID, "crappium_axe", BadOres.TAB, ModToolMaterial.CRAPPIUM, 6f, -3.2f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_HOE = new ModItemHoeBase(BadOres.MODID, "crappium_hoe", BadOres.TAB, ModToolMaterial.CRAPPIUM, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_HELMET = new ModItemArmorBase(BadOres.MODID, "crappium_helmet", BadOres.TAB, ModArmorMaterial.CRAPPIUM, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_CHESTPLATE = new ModItemArmorBase(BadOres.MODID, "crappium_chestplate", BadOres.TAB, ModArmorMaterial.CRAPPIUM, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_LEGGINGS = new ModItemArmorBase(BadOres.MODID, "crappium_leggings", BadOres.TAB, ModArmorMaterial.CRAPPIUM, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item CRAPPIUM_BOOTS = new ModItemArmorBase(BadOres.MODID, "crappium_boots", BadOres.TAB, ModArmorMaterial.CRAPPIUM, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item ENDERITE_SWORD = new ItemEnderiteSword(BadOres.MODID, "enderite_sword", BadOres.TAB, ModToolMaterial.ENDERITE, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_SHOVEL = new ItemEnderiteShovel(BadOres.MODID, "enderite_shovel", BadOres.TAB, ModToolMaterial.ENDERITE, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_PICKAXE = new ItemEnderitePickaxe(BadOres.MODID, "enderite_pickaxe", BadOres.TAB, ModToolMaterial.ENDERITE, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_AXE = new ItemEnderiteAxe(BadOres.MODID, "enderite_axe", BadOres.TAB, ModToolMaterial.ENDERITE, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_HOE = new ItemEnderiteHoe(BadOres.MODID, "enderite_hoe", BadOres.TAB, ModToolMaterial.ENDERITE, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_HELMET = new ItemEnderiteArmor(BadOres.MODID, "enderite_helmet", BadOres.TAB, ModArmorMaterial.ENDERITE, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_CHESTPLATE = new ItemEnderiteArmor(BadOres.MODID, "enderite_chestplate", BadOres.TAB, ModArmorMaterial.ENDERITE, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_LEGGINGS = new ItemEnderiteArmor(BadOres.MODID, "enderite_leggings", BadOres.TAB, ModArmorMaterial.ENDERITE, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item ENDERITE_BOOTS = new ItemEnderiteArmor(BadOres.MODID, "enderite_boots", BadOres.TAB, ModArmorMaterial.ENDERITE, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item AMADEUM_SWORD = new ItemAmadeumSword(BadOres.MODID, "amadeum_sword", BadOres.TAB, ModToolMaterial.AMADEUM, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_SHOVEL = new ItemAmadeumShovel(BadOres.MODID, "amadeum_shovel", BadOres.TAB, ModToolMaterial.AMADEUM, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_PICKAXE = new ItemAmadeumPickaxe(BadOres.MODID, "amadeum_pickaxe", BadOres.TAB, ModToolMaterial.AMADEUM, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_AXE = new ItemAmadeumAxe(BadOres.MODID, "amadeum_axe", BadOres.TAB, ModToolMaterial.AMADEUM, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_HOE = new ItemAmadeumHoe(BadOres.MODID, "amadeum_hoe", BadOres.TAB, ModToolMaterial.AMADEUM, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_HELMET = new ItemAmadeumArmor(BadOres.MODID, "amadeum_helmet", BadOres.TAB, ModArmorMaterial.AMADEUM, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_CHESTPLATE = new ItemAmadeumArmor(BadOres.MODID, "amadeum_chestplate", BadOres.TAB, ModArmorMaterial.AMADEUM, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_LEGGINGS = new ItemAmadeumArmor(BadOres.MODID, "amadeum_leggings", BadOres.TAB, ModArmorMaterial.AMADEUM, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item AMADEUM_BOOTS = new ItemAmadeumArmor(BadOres.MODID, "amadeum_boots", BadOres.TAB, ModArmorMaterial.AMADEUM, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item COPPER_SWORD = new ModItemSwordBase(BadOres.MODID, "copper_sword", BadOres.TAB, ModToolMaterial.COPPER, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_SHOVEL = new ModItemShovelBase(BadOres.MODID, "copper_shovel", BadOres.TAB, ModToolMaterial.COPPER, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_PICKAXE = new ModItemPickaxeBase(BadOres.MODID, "copper_pickaxe", BadOres.TAB, ModToolMaterial.COPPER, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_AXE = new ModItemAxeBase(BadOres.MODID, "copper_axe", BadOres.TAB, ModToolMaterial.COPPER, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_HOE = new ModItemHoeBase(BadOres.MODID, "copper_hoe", BadOres.TAB, ModToolMaterial.COPPER, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_HELMET = new ModItemArmorBase(BadOres.MODID, "copper_helmet", BadOres.TAB, ModArmorMaterial.COPPER, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_CHESTPLATE = new ModItemArmorBase(BadOres.MODID, "copper_chestplate", BadOres.TAB, ModArmorMaterial.COPPER, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_LEGGINGS = new ModItemArmorBase(BadOres.MODID, "copper_leggings", BadOres.TAB, ModArmorMaterial.COPPER, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item COPPER_BOOTS = new ModItemArmorBase(BadOres.MODID, "copper_boots", BadOres.TAB, ModArmorMaterial.COPPER, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item NOPIUM_SWORD = new ItemNopiumSword(BadOres.MODID, "nopium_sword", BadOres.TAB, ModToolMaterial.NOPIUM, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_SHOVEL = new ItemNopiumShovel(BadOres.MODID, "nopium_shovel", BadOres.TAB, ModToolMaterial.NOPIUM, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_PICKAXE = new ItemNopiumPickaxe(BadOres.MODID, "nopium_pickaxe", BadOres.TAB, ModToolMaterial.NOPIUM, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_AXE = new ItemNopiumAxe(BadOres.MODID, "nopium_axe", BadOres.TAB, ModToolMaterial.NOPIUM, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_HOE = new ItemNopiumHoe(BadOres.MODID, "nopium_hoe", BadOres.TAB, ModToolMaterial.NOPIUM, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_HELMET = new ItemNopiumArmor(BadOres.MODID, "nopium_helmet", BadOres.TAB, ModArmorMaterial.NOPIUM, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_CHESTPLATE = new ItemNopiumArmor(BadOres.MODID, "nopium_chestplate", BadOres.TAB, ModArmorMaterial.NOPIUM, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_LEGGINGS = new ItemNopiumArmor(BadOres.MODID, "nopium_leggings", BadOres.TAB, ModArmorMaterial.NOPIUM, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item NOPIUM_BOOTS = new ItemNopiumArmor(BadOres.MODID, "nopium_boots", BadOres.TAB, ModArmorMaterial.NOPIUM, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item CRASHIUM_SWORD = new ItemCrashiumSword(BadOres.MODID, "crashium_sword", BadOres.TAB, ModToolMaterial.CRASHIUM, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_SHOVEL = new ItemCrashiumShovel(BadOres.MODID, "crashium_shovel", BadOres.TAB, ModToolMaterial.CRASHIUM, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_PICKAXE = new ItemCrashiumPickaxe(BadOres.MODID, "crashium_pickaxe", BadOres.TAB, ModToolMaterial.CRASHIUM, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_AXE = new ItemCrashiumAxe(BadOres.MODID, "crashium_axe", BadOres.TAB, ModToolMaterial.CRASHIUM, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_HOE = new ItemCrashiumHoe(BadOres.MODID, "crashium_hoe", BadOres.TAB, ModToolMaterial.CRASHIUM, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_HELMET = new ItemCrashiumArmor(BadOres.MODID, "crashium_helmet", BadOres.TAB, ModArmorMaterial.CRASHIUM, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_CHESTPLATE = new ItemCrashiumArmor(BadOres.MODID, "crashium_chestplate", BadOres.TAB, ModArmorMaterial.CRASHIUM, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_LEGGINGS = new ItemCrashiumArmor(BadOres.MODID, "crashium_leggings", BadOres.TAB, ModArmorMaterial.CRASHIUM, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item CRASHIUM_BOOTS = new ItemCrashiumArmor(BadOres.MODID, "crashium_boots", BadOres.TAB, ModArmorMaterial.CRASHIUM, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item SMITE_SWORD = new ItemSmiteSword(BadOres.MODID, "smite_sword", BadOres.TAB, ModToolMaterial.SMITE, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_SHOVEL = new ItemSmiteShovel(BadOres.MODID, "smite_shovel", BadOres.TAB, ModToolMaterial.SMITE, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_PICKAXE = new ItemSmitePickaxe(BadOres.MODID, "smite_pickaxe", BadOres.TAB, ModToolMaterial.SMITE, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_AXE = new ItemSmiteAxe(BadOres.MODID, "smite_axe", BadOres.TAB, ModToolMaterial.SMITE, 8f, -3.1f, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_HOE = new ItemSmiteHoe(BadOres.MODID, "smite_hoe", BadOres.TAB, ModToolMaterial.SMITE, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_HELMET = new ItemSmiteArmor(BadOres.MODID, "smite_helmet", BadOres.TAB, ModArmorMaterial.SMITE, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_CHESTPLATE = new ItemSmiteArmor(BadOres.MODID, "smite_chestplate", BadOres.TAB, ModArmorMaterial.SMITE, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_LEGGINGS = new ItemSmiteArmor(BadOres.MODID, "smite_leggings", BadOres.TAB, ModArmorMaterial.SMITE, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item SMITE_BOOTS = new ItemSmiteArmor(BadOres.MODID, "smite_boots", BadOres.TAB, ModArmorMaterial.SMITE, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item DIAMOND_SWORD = new ModItemSwordBase(BadOres.MODID, "diamond_sword", BadOres.TAB, ModToolMaterial.DIAMOND, 3f, -2.4f, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_SHOVEL = new ModItemShovelBase(BadOres.MODID, "diamond_shovel", BadOres.TAB, ModToolMaterial.DIAMOND, 1.5f, -3f, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_PICKAXE = new ModItemPickaxeBase(BadOres.MODID, "diamond_pickaxe", BadOres.TAB, ModToolMaterial.DIAMOND, 1f, -2.8f, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_AXE = new ModItemAxeBase(BadOres.MODID, "diamond_axe", BadOres.TAB, ModToolMaterial.DIAMOND, 6f, -3.2f, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_HOE = new ModItemHoeBase(BadOres.MODID, "diamond_hoe", BadOres.TAB, ModToolMaterial.DIAMOND, -2f, -1f, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_HELMET = new ItemDiamondArmor(BadOres.MODID, "diamond_helmet", BadOres.TAB, ModArmorMaterial.DIAMOND, 0, EntityEquipmentSlot.HEAD, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_CHESTPLATE = new ItemDiamondArmor(BadOres.MODID, "diamond_chestplate", BadOres.TAB, ModArmorMaterial.DIAMOND, 0, EntityEquipmentSlot.CHEST, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_LEGGINGS = new ItemDiamondArmor(BadOres.MODID, "diamond_leggings", BadOres.TAB, ModArmorMaterial.DIAMOND, 1, EntityEquipmentSlot.LEGS, ModRarities.WHITE, false, 0, 0);
	public static final Item DIAMOND_BOOTS = new ItemDiamondArmor(BadOres.MODID, "diamond_boots", BadOres.TAB, ModArmorMaterial.DIAMOND, 0, EntityEquipmentSlot.FEET, ModRarities.WHITE, false, 0, 0);

	public static final Item MARMITE_BREAD = new ModItemFoodBase(BadOres.MODID, "marmite_bread", BadOres.TAB, 8, 0.75f, false, ModRarities.WHITE, false, 0, 0);
}